# Generated by Django 4.0.4 on 2022-05-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='apply',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
